// Generated by nitro

// App Config
import type { Defu } from 'defu'

import type { default as appConfig0 } from "C:/Users/Nebula PC/Desktop/BearScore/.app/app.config";
import type { default as appConfig1 } from "C:/Users/Nebula PC/Desktop/BearScore/layers/tairo-layout-sidebar/app.config";
import type { default as appConfig2 } from "C:/Users/Nebula PC/Desktop/BearScore/layers/tairo-layout-collapse/app.config";
import type { default as appConfig3 } from "C:/Users/Nebula PC/Desktop/BearScore/layers/tairo-layout-topnav/app.config";
import type { default as appConfig4 } from "C:/Users/Nebula PC/Desktop/BearScore/layers/tairo/app.config";
import type { default as appConfig5 } from "C:/Users/Nebula PC/Desktop/BearScore/node_modules/.pnpm/@shuriken-ui+nuxt@3.1.5_nuxt@3.11.2_vue@3.4.21/node_modules/@shuriken-ui/nuxt/app.config";

type UserAppConfig = Defu<{}, [typeof appConfig0, typeof appConfig1, typeof appConfig2, typeof appConfig3, typeof appConfig4, typeof appConfig5]>

declare module 'nitropack' {
  interface AppConfig extends UserAppConfig {}
}
    
export {}